FROM node:18-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

ARG REACT_APP_MAPBOX_TOKEN
ARG REACT_APP_GOOGLEMAPS_TOKEN
ARG REACT_APP_MAP_ID

ENV REACT_APP_MAPBOX_TOKEN=$REACT_APP_MAPBOX_TOKEN
ENV REACT_APP_GOOGLEMAPS_TOKEN=$REACT_APP_GOOGLEMAPS_TOKEN
ENV REACT_APP_MAP_ID=$REACT_APP_MAP_ID

RUN npm run build

FROM nginx:alpine

COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]